### ISSUE TITLE
Documentation for Data Entry

### ISSUE THREAD

**Issue by rshaferw** [hivdb/covid-drdb-payload#10]

**Comment by KaimingTao** [comment]
Suggestions about https://github.com/hivdb/covid-drdb-payload/wiki/Entering-neutralization-data-(plasma)

1. we may link `isolates` and `variants` parts to https://github.com/hivdb/covid-drdb-payload/wiki/Method:-Variants,-isolates-and-mutations
2. We may remove some examples because they take too much space.
3. `cumulative_group` just copy the value of `subject_name`
4. We may indicate the `primary key` of each table.
5. NT50 in a paper can be from a table, a sigmoid figure, a point figure(paired, unpaired)

**Comment by KaimingTao** [comment]
[mAb_template.xlsx](https://github.com/hivdb/covid-drdb-payload/files/8931853/mAb_template.xlsx)

**Comment by KaimingTao** [comment]
[plasma_template.xlsx](https://github.com/hivdb/covid-drdb-payload/files/8932789/plasma_template.xlsx)
