### ISSUE TITLE
Iota and Iota w/o E484K

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#103]
The Outbreak.Info is now has Iota's consensus without E484K. We should rename these three variants accordingly:

- Iota => Iota/E484K
- Iota w/o E484K => Iota
- Iota/S477N w/o E484K => Iota/S477N

Attachment (Outbreak.Info):

<img width="532" alt="Screen Shot 2022-01-21 at 9 59 23 AM" src="https://user-images.githubusercontent.com/809865/150577002-8aab6312-b60f-4bd8-95b1-70bb4bae9871.png">

**Comment by KaimingTao** [comment]
There's one issue of renaming the spike mutation list of one variant. The neutralization test (pseudovirus assay) in a paper means the neutralization effect of plasma or monoclonal antibody on one particular spike mutation combination. If we change the spike mutation list of a VOI depending on the statistical result of a newly generated spike mutation list, the meaning will change. Especially for RBM mutations which will affect monoclonal antibodies.

The mutation list on outbreak.info reflects the latest analysis of all accessible sequences, so it's always changing, but the pseudovirus used in a paper won't change.

Since most of the time, we show the VOI name on the website, we may need some discussion about this issue.

**Comment by philiptzou** [comment]
@KaimingTao I don't expect and want to have this change affect our previous data. This can be just a **superficial** change. How about we also rename the current isolate names?

- B.1.526 Spike => B.1.526/E484K Spike
- B.1.526 v.2 Spike => B.1.526/S477N Spike

You can have another B.1.526 Spike to represent the consensus of B.1.526 (without E484K and S477N) if it's needed.

**Comment by KaimingTao** [comment]
> @KaimingTao I don't expect and want to have this change affect our previous data. This can be just a **superficial** change. How about we also rename the current isolate names?
> 
> * B.1.526 Spike => B.1.526/E484K Spike
> * B.1.526 v.2 Spike => B.1.526/S477N Spike
> 
> You can have another B.1.526 Spike to represent the consensus of B.1.526 (without E484K and S477N) if it's needed.

That could solve this issue.

Currently, we can keep any variant's reference spike mutation list as 1) commonly used in papers, 2) the latest consensus from sequence analysis (like outbreak.info).

That happened to Omicron, the commonly used spike mutation list (same as our variant page) in papers is different from the outbreak.info analysis, because Omicron is changing. Even pangolin assigned a new name for most of Omicron to BA.1 it's different from the commonly used mutations in papers.

My question could be should we also use the same method for Omicron? We may need to define a common method for all variants.

**Comment by philiptzou** [comment]
@KaimingTao Maybe. If we had to use the consensus to represent a variant from a paper, we should take the publish date into consideration.

Since you agree with this approach for Iota, let's fix Iota first. We can open another issue to discuss Omicron.
