### ISSUE TITLE
Discuss about papers

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/covid-drdb-payload#17]

**Comment by rshaferw** [comment]
1. Paper by Wu describing two different mRNA-1273 boosters. How to represent. ? develop a unique name for the regimen and provide an explanation for the name below the table.

**Comment by rshaferw** [comment]
2. AZD2816 paper by Spencer - How will we indicate that the antibodies are from vaccinated animals?
3. Vaccine cards for AZD2816 and mRNA-1273(B.1.351)
4. Behrens - Lancet - SARS-CoV-2 delta variant neutralisation after heterologous ChAdOx1-S/BNT162b2 vaccination. ? create a vaccine type "ChAdOx1-S/BNT162b2" with an explanatory footnote (extracted from our vaccine table).
5. Barros-Martins (senior author Behrens) Nature Medicine (https://www.nature.com/articles/s41591-021-01449-9) - Note: This paper and the preceding one use a sVNT assay (s=~soluble) in which the antibody is tested for blocking Ab / ACE2 binding. This is increasingly used because it is high throughput. We should create this assay in the database and add studies that use it.
6. Acevedo - Research Square paper has additional data not present in the Acevedo BioRxiv paper. It contains data for BNT162b.

**Comment by rshaferw** [comment]
- [ ] Peiffer-Smadja. Emergence of E484K Mutation Following Bamlanivimab Monotherapy among High-Risk Patients Infected with the Alpha Variant of SARS-CoV-2. 10.3390/v13081642. In vivo selection of mutations with bamlanivimab.

**Comment by rshaferw** [comment]
- [ ] Neumann. Development of SARS-CoV-2 Specific IgG and Virus-Neutralizing Antibodies after Infection with Variants of Concern or Vaccination. 10.3390/vaccines9070700. Figure 4a (sVNT). Figure 5 (cVNT) [c=vero cell based neutralization test == live virus]

**Comment by rshaferw** [comment]
- [ ] Fernandez J. Neutralization of Alpha, Gamma, and D614G SARS-CoV-2 variants by CoronaVac vaccine-induced antibodies. Clin Infect Dis. VP (coronovac) vs 614G, alpha, gamma

**Comment by KaimingTao** [comment]
> * Wilhelm pre-print. Antibody mediated neutralization of authentic SARS-CoV-2 B.1.617 variants harboring L452R and T478K/E484Q. 10.1101/2021.08.09.21261704. Figures 1 and 2

Figure 2 contains mab IC50 results but it's using serial dilution method. It's different with common mAb experiments which using ng/ml to measure the result.

**Comment by rshaferw** [comment]
- [ ] Tang J. Epitope diversity of SARS-CoV-2 hyperimmune intravenous human immunoglobulins and neutralization of variants of concern. iScience. This deals with IVIG. We should add this to those list of papers to keep in our radar. But we should not add this yet.

**Comment by KaimingTao** [comment]
> * [ ]  Hadjadj pre-print (lower priority). Immunogenicity of BNT162b2 vaccine Against the Alpha and Delta Variants in Immunocompromised Patients. 10.1101/2021.08.08.21261766. Figure 2C. But how to represent the immunocompromised patients???

@rshaferw currently we can mark the immunocompomised patients by subject name, another way is to add a new field in subjects table.

**Comment by KaimingTao** [comment]
> * [x]  Chen, L. Emergence of Multiple SARS-CoV-2 Antibody Escape Variants in an Immunocompromised Host Undergoing Convalescent Plasma Treatment. 10.1128/mSphere.00480-21. Prolonged infection with emergent mutations. We should discuss placing them in the database - **in vivo selection**.

It's an update of 10.1101/2021.04.08.21254791

**Comment by KaimingTao** [comment]
> * [x]  Neumann. Development of SARS-CoV-2 Specific IgG and Virus-Neutralizing Antibodies after Infection with Variants of Concern or Vaccination. 10.3390/vaccines9070700. Figure 4a (sVNT). Figure 5 (cVNT) [c=vero cell based neutralization test == live virus]

Figure 4a, sVNT is not represented as titer but percentage of inhibition, it's different with other sVNT studies.
