### ISSUE TITLE
Wu21c titers appear to be low

### ISSUE THREAD

**Issue by rshaferw** [hivdb/covid-drdb-payload#62]
**Describe the error**
We should review because the titers appear to be low - just above 40. Not <40 or <27. 
In addition, I think the months for both groups are about 6.

**Comment by philiptzou** [comment]
The number "27" is from the number above the B.1.351 box from Figure 3A, the mRNA1273 group, but not Figure 3C, the mRNA1273.351 group. All the numbers look good to me.

Here are the issues:

1. The detection threshold (LLOQ, dotted line on the figures) looks like 20 (10<sup>1.3</sup> ≈ 20). [The `potency_lower_limit` column shows 110](https://github.com/hivdb/covid-drdb-payload/blob/ac23491/tables/rx_potency/wu21c-pot.csv).
2. The time intervals is switched between mRNA1273 and mRNA1273.351 group [here](https://github.com/hivdb/covid-drdb-payload/blob/4893bf9/tables/subject_history/wu21c-pth.csv).
   1. For mRNA1273 group, the mean & median time interval between 2nd dose and 3rd booster are 201 and 196 days. However, the time interval from our table is 187 days (from 2020-07-08 to 2021-01-11).
   2. The same thing happens to mRNA1273.351 group too: the mean & median are 187.1 and 189.1 days, the time interval from our table is 201 days.
3. Results from Figure 3A and 3C can not be merged, because 187 days fall into 6 month which belongs to aggregation group 2-6 months; 201 days fall into 7 month which belongs to aggregation group >7 months.


Table 1:
![image](https://user-images.githubusercontent.com/809865/133947568-a5569d14-7d66-4f66-8d3c-7484cd59a65e.png)

Figure 3:
![image](https://user-images.githubusercontent.com/809865/133947754-11f2212b-e090-46c9-b41a-3f31e948112f.png)
![image](https://user-images.githubusercontent.com/809865/133947759-e0e8e507-f1f0-4af6-802b-9a79a66433e6.png)

**Comment by philiptzou** [comment]
Addressed the time intervals issue in fe5e505.

**Comment by philiptzou** [comment]
Commit hivdb/chiro-cms@7150328 has addressed the month aggregation group issue. This ticket is resolved.

<img width="1375" alt="Screen Shot 2021-09-19 at 11 44 31 PM" src="https://user-images.githubusercontent.com/809865/133964782-205f53c7-4b6f-47cf-a59e-796e54f8706d.png">
