### ISSUE TITLE
This is a major Bug - Omicron/701V should not be different from Omicron. All of the Omicrons should be together. We are sabotaging the usefulness of the database by separating these out.

### ISSUE THREAD

**Issue by rshaferw** [hivdb/covid-drdb-payload#94]
<img width="1380" alt="Screen Shot 2021-12-30 at 3 00 03 PM" src="https://user-images.githubusercontent.com/8672489/147793249-f9db5097-3838-4e17-9c70-fdf37b6951b5.png">

**Comment by philiptzou** [comment]
@KaimingTao I don't think A701V is qualified to be added according to our own rule. Why you think it's an important mutation?

The rule: https://github.com/hivdb/covid-drdb-payload/wiki/Variants,-isolates-and-mutations#variant-modifiers-the-rationale-and-when-to-use

**Comment by MacGregorCox** [comment]
R346K could potentially be a resistance mutation. - and therefore meet the criteria for being included as a seperate variant.

In the dataset from 24thDec, where Omicron and Omicron/R346K are seperated we have: 
Assays of Omicron and Sotrovimab Fold Change - range 2.8-6x 
Single assay of Omicron/R346K Fold Change- 48.9x. 

Since this would Omicron/R346K resistant to all currently available mAb treatments its important to be able to segregate the data in this way.

**Comment by philiptzou** [comment]
Reopen for further discussion. I agree that R346K should be separated from current pooled Omicron.

**Comment by KaimingTao** [comment]
@MacGregorCox 
The Omicron/R346K is isolated from Omicron, this issue is fixed here: https://github.com/hivdb/covid-drdb-payload/commit/4497c1e09ce7c1933d20f5d301d5e902bb1e3252. The data is published on the [website](https://covdb.stanford.edu/search-drdb/?dosage=2&dosage=3&host=human&variant=Omicron%2FR346K), and also published in [pre-release](https://github.com/hivdb/covid-drdb-payload/releases/tag/20220124-101527) SQLite version.

**Comment by KaimingTao** [comment]
This issue is also related to the discussion in issue #103 about the consensus mutations of Omicron spike. If in the future the consensus of omicron is changed because some mutations are widely spread, the definition of Omicron may not be changed, because it will conflict with references' results.

**Comment by philiptzou** [comment]
@KaimingTao The definition never changes. We just need to rename them. E.g. Omicron => Omicron w/o R346K, Omicron/R346K => Omicron and also the isolate names.
